project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

website:
  navbar:
    background: light
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: Research.qmd
      - text: "Posters"
        file: Posters.qmd
      - text: "Publications"
        file: Publications.qmd

