project:
  type: website
  output-dir: docs

website:
  title: "ajloud-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: Publications.qmd
        text: Publications
      - href: Posters.qmd
        text: Posters

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

